source 'http://artifactory.mia.ucloud.int/artifactory/api/gems/rubygems'
source 'http://artifactory.mia.ucloud.int/artifactory/api/gems/ultimate-local'

gem 'rake', '~> 10.4.0'
gem 'archive-zip'
gem 'deployment_utils'
gem 'spade-client'
gem 'table_print'
gem 'json', '~> 1.8.0'
gem 'berkshelf', '~> 2.0.0' # DO NOT UPDATE to 3.00
gem 'celluloid', '~> 0.16.0'

