source 'http://artifactory.mia.ucloud.int/artifactory/api/gems/rubygems'
source 'http://artifactory.mia.ucloud.int/artifactory/api/gems/ultimate-local'

gem 'rake', '~> 10.4.0'
gem 'archive-zip'
gem 'deployment_utils'
gem 'berkshelf', '~> 2.0.0' # DO NOT UPDATE to 3.00


